#!/usr/bin/env python3
"""Enforce PR scope for the Caelestia plugin store.

The store rule is "one folder, one plugin": every plugin lives in its own
directory under ``plugins/``. A plugin PR must only touch files under
``plugins/`` - index.json is regenerated by CI and root files (docs, scripts,
workflows) change in their own PRs.

This script fails when a diff between a base ref and HEAD touches anything
outside ``plugins/`` (or an explicitly allowed path).

Usage:
    python scripts/check_scope.py --base origin/main
    python scripts/check_scope.py --base <base-sha> --allow index.json

CI passes ``github.event.pull_request.base.sha`` as ``--base``.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def changed_paths(base: str, repo: Path) -> list[str]:
    """Return paths changed on HEAD relative to ``base`` (three-dot diff)."""
    out = subprocess.check_output(
        ["git", "-C", str(repo), "diff", "--name-only",
         "--diff-filter=ACMRT", f"{base}...HEAD"],
        text=True,
    )
    return [line.strip() for line in out.splitlines() if line.strip()]


def is_allowed(path: str, allow: list[str]) -> bool:
    for prefix in allow:
        prefix = prefix.strip("/")
        if path == prefix or path.startswith(prefix + "/"):
            return True
    return False


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", required=True,
                        help="base ref/sha to diff against (three-dot) with HEAD")
    parser.add_argument("--repo", default=str(REPO_ROOT),
                        help="path to the repository (defaults to this repo)")
    parser.add_argument("--allow", action="append", default=[],
                        help="extra path prefix to allow (repeatable)")
    args = parser.parse_args(argv)

    repo = Path(args.repo)
    changed = changed_paths(args.base, repo)

    bad = []
    for path in changed:
        if is_allowed(path, ["plugins"] + args.allow):
            continue
        bad.append(path)

    if bad:
        print("error: PR changes files outside plugins/:", file=sys.stderr)
        for path in bad:
            print(f"  {path}", file=sys.stderr)
        print(
            "hint: the store is 'one folder, one plugin'. Move non-plugin "
            "changes (docs, scripts, workflows, root .gitignore, index.json) "
            "to a separate PR.",
            file=sys.stderr,
        )
        return 1

    print(f"OK: {len(changed)} changed file(s), all under plugins/.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
